
import 'bootstrap/dist/css/bootstrap.min.css';
import ThemeProvider from "@/context/ThemeProvider"
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import React from "react";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
            <Header />
            {children}
            <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
